// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKJEANguCDTaswcaS6OXYM1nyFrWFvVao',
    appId: '1:449350149768:web:6f8e05d034ea632843213d',
    messagingSenderId: '449350149768',
    projectId: 'brahmakosh-7a66d',
    authDomain: 'brahmakosh-7a66d.firebaseapp.com',
    storageBucket: 'brahmakosh-7a66d.firebasestorage.app',
    measurementId: 'G-58GBQY32QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nNdCNACG7UKBLwigMcJ0poDmLJdj3Gw',
    appId: '1:449350149768:android:6fee880380525f0c43213d',
    messagingSenderId: '449350149768',
    projectId: 'brahmakosh-7a66d',
    storageBucket: 'brahmakosh-7a66d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXDNXRxCPN-Em-92PIrmvUzcnv0kjojcg',
    appId: '1:449350149768:ios:4f9daaa5437ea50543213d',
    messagingSenderId: '449350149768',
    projectId: 'brahmakosh-7a66d',
    storageBucket: 'brahmakosh-7a66d.firebasestorage.app',
    iosBundleId: 'com.brahmakosh.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXDNXRxCPN-Em-92PIrmvUzcnv0kjojcg',
    appId: '1:449350149768:ios:4f9daaa5437ea50543213d',
    messagingSenderId: '449350149768',
    projectId: 'brahmakosh-7a66d',
    storageBucket: 'brahmakosh-7a66d.firebasestorage.app',
    iosBundleId: 'com.brahmakosh.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKJEANguCDTaswcaS6OXYM1nyFrWFvVao',
    appId: '1:449350149768:web:3cfa988f2fce9c3643213d',
    messagingSenderId: '449350149768',
    projectId: 'brahmakosh-7a66d',
    authDomain: 'brahmakosh-7a66d.firebaseapp.com',
    storageBucket: 'brahmakosh-7a66d.firebasestorage.app',
    measurementId: 'G-GT8EE23BKZ',
  );
}
